import {StyleSheet, Dimensions} from 'react-native';

export default StyleSheet.create({
  container: {
    alignItems: 'center',
    flex: 1,
  },
  sub_container: {
    flex: 0.12,
    margin: 5,
    height: Dimensions.get('screen').height / 22,
    width: Dimensions.get('screen').width / 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Dimensions.get('screen').width / 60,
  },
  methodButton: {
    flex: 1,
    padding: 10,
    height: Dimensions.get('screen').height / 13,
    margin: 3,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bt_text: {
    color: 'white',
    fontWeight: 'bold',
  },
  selectedMethodContainer: {
    alignItems: 'center',
  },
  selectedMethodText: {
    marginTop: 15,
    fontSize: 16,
    color: 'black',
  },
  container2: {
    flex: 1,
  },
  inputContainer: {
    borderRadius: 10,
    marginBottom: 20,
    marginTop: 20,
    alignItems: 'center',
  },
  result: {
    textAlign: 'center',
    borderRadius: 10,
    fontSize: 24,
    fontWeight: 'bold',
    borderWidth: 1,
    marginBottom: 10,
    width: Dimensions.get('window').width / 1.5,
  },
  buttonContainer: {
    width: '70%',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  button: {
    margin: 2,
    borderWidth: 1,
    borderRadius: 10,
    width: Dimensions.get('window').width / 5,
    height: Dimensions.get('window').height / 11.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'darkblue',
  },
  bot_top_buttons: {
    marginHorizontal: 2,
    marginVertical: 2,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'darkblue',
    width: Dimensions.get('window').width / 2.45,
  },
  modal_title: {
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
    margin: 10,
  },
  prd_cont: {
    flex: 1,
    margin: 5,
    borderColor: 'black',
    borderWidth: 1,
  },
  total_text: {
    fontSize: 18,
    color: 'black',
  },
  cart_container: {
    flex: 1,
    margin: 5,
  },
  selected_item: {
    backgroundColor: '#e0e0e0',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  input: {
    height: 40,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 10,
    marginBottom: 20,
    width: '100%',
  },
  modalButton: {
    borderRadius: 50,
    padding: 10,
    elevation: 2,
    width: '100%',
    marginBottom: 10,
    alignItems: 'center',
  },
  text_button: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
